### ISSUE TITLE
Suggestion: add require vcc repos in the readme

### ISSUE THREAD

**Issue by DammitStella** [Spokeek/vrchat-ndmf-template-project#1]
If you have a fresh install of VCC, the templates errors out if you don't have the following VPM repos added:
Nadena (Modular Avatar/ndmf)
Rs64 (TexTransTool)
Anatawa (Avatar-Optimizer)
Dreadscripts (Hierachy Plus)
Narazaka (avatar-menu-creater-for-ma)
![the needed repos](https://github.com/Spokeek/vrchat-ndmf-template-project/assets/5460892/cf8d5548-f4a4-4933-a133-c8662a733412)

**Comment by Spokeek** [comment]
This is true. I know there is the "Package Installer" Package that can prompt you to install missing dependencies, there is the "official" from vrchat and one from the vrc-get team, but i don't know if it works for custom repositories. I'll investigate.

Thank you for the reminder.
